baseURL = "https://www.fish-king.site/"
title = "Fish King" # 使用了你的主要标题
theme = "ladder"
license = "MIT"
licenselink = "https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE"
description = "My site description"
homepage = "https://www.fish-king.site/"
# 设置默认语言为中文
defaultContentLanguage = "zh"
pagination.pagerSize = 10

# Google Analytics (如有需要请替换 G-xxx)
googleAnalytics = "G-xxx" 

[params]
brand = "Fish King" # 导航栏左上角显示的文字
avatarURL = "/images/profile.jpg" # 对应你原来的 authorImage
author = "Fish King"
authorDescription = "I'm fish, nice to meet you(ˊ˘ˋ*)♡" # 对应你原来的 content
info = "My site description" # 对应你原来的 description
favicon = "/images/profile.jpg" # 默认使用头像作为 favicon
darkModeTheme = "data-dark-mode"

  [params.options]
  showDarkMode = true
  enableImgZooming = true
#   enableMultiLang = true
  showMetaTags = true

# --- 评论系统设置 ---
[params.comments.giscus]
enable = true
# 请取消注释并填入你的信息
# repo = "hotjuicew/blog"
# repo_id = "R_kgDOHHQOuw"
# category = "Announcements"
# category_id = "DIC_kwDOHHQOu84CWCQ3"
mapping = "og:title"
position = "bottom"
lang = "zh-CN"

[params.comments.utteranc]
enable = false
repo = "username/reponame"
issueTerm = "pathname"

# --- 统计工具 ---
[params.analytics.google]
SiteVerificationTag = "xxx"

[params.analytics.umami]
enable = true
# 填入你原来的 Dashboard 链接中的 ID
website_id = "xxx" 
url = "https://umami-ochre-nu.vercel.app/hugo-ladder.js"

#   [params.guestbook]
#   title = "留言板"
#   description = "欢迎留下你的评论、问题或建议。"

  # --- 社交链接 (已为你补充 SVG 图标) ---
  
#   [[params.social]]
#   name = "GitHub"
#   # GitHub 图标
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
#   url = "https://github.com/hotjuicew"

#   [[params.social]]
#   name = "Telegram"
#   # Telegram 图标 (纸飞机)
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-send"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>'
#   url = "https://t.me/Hotjuice"

#   [[params.social]]
#   name = "Twitter"
#   # Twitter 图标
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>'
#   url = "https://twitter.com/hotjuicee"

#   [[params.social]]
#   name = "Email"
#   # Email 图标
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>'
#   url = "mailto:imjiaying@outlook.com"

# --- 语言与菜单配置 ---

# 中文设置 (默认)
[languages.zh]
languageName = "中文"
author = "Fish King"
authorDescription = "I'm fish, nice to meet you(ˊ˘ˋ*)♡"
info = "My site description"

#   [languages.zh.guestbook]
#   title = "留言板"
#   description = "欢迎留下你的评论(ˊ˘ˋ*)♡"

[[languages.zh.menu.main]]
name = "文章"
url = "/post" 
weight = 1

[[languages.zh.menu.main]]
name = "标签"
url = "/tags"
weight = 2

[[languages.zh.menu.main]]
name = "归档"
url = "/archives"
weight = 3

# [[languages.zh.menu.main]]
# name = "留言板"
# url = "/guestbook"
# weight = 4

# [[languages.zh.menu.main]]
# name = "统计"
# url = "https://umami-ochre-nu.vercel.app/share/R1lHz7QY/hugo-ladder-exampleSite"
# weight = 5

# 英文设置 (保留以备不时之需，不需要可以删除)
[languages.en]
languageName = "En"
author = "Fish King"
authorDescription = "I'm fish, nice to meet you(ˊ˘ˋ*)♡"

[[languages.en.menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[[languages.en.menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[languages.en.menu.main]]
name = "Archive"
url = "/archives"
weight = 3

[taxonomies]
series = "series"
tag = "tags"
category = "categories"